### ISSUE TITLE
Smartwatt and power API version

### ISSUE THREAD

**Issue by PierreRustOrange** [powerapi-ng/smartwatts-formula#18]
I have some issues with smartwatt and powerapi versioning scheme: 
* On the docker Hub, the last release version of smartwatt is 0.8.4 : https://hub.docker.com/r/powerapi/smartwatts-formula/tags
* According to the release notes, smartwatt 0.8.4 uses power api 1.0.2 https://github.com/powerapi-ng/smartwatts-formula/releases/tag/v0.8.4
* However, in the smartwatt repository, the dockerfile (for the 0.8.4 tag) is based on powerapi 0.9.3 :  https://github.com/powerapi-ng/smartwatts-formula/blob/v0.8.4/Dockerfile-cpython

On top of that powerapi is now on 1.0.4, which contains interesting changes on metadata and reports, but is not used by any smartwatt version.

I can only guess that your development setup, and your CI - publish setups, don't actually use the Dockerfile published in the repository, but this makes it very difficult to keep track of versions and make sure I have a dev environment that matches what you are using.

BTW, there is a similar issue with the build mechanism of the sensor : powerapi-ng/hwpc-sensor#19

**Comment by gfieni** [comment]
There were indeed issues regarding the dependency versions handling, and these problems have been fixed with the rework of the Continuous Integration.
The builds and releases workflows now use the same environment, and the library versions (python, container image) are now automatically updated by dependabot.

Thanks for reporting these problems.
