### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by msalvati1997** [powerapi-ng/smartwatts-formula#29]
Hello!
I think there is a lack of documentation regarding the meaning of smartwatts results in a database.
What does 'global' and the respective powers? Is it the power consumed globally? So if you want to know the total power consumed by the local node, you have to exclude global if you only want to consider containers and other applications? Thank you in advance. 
![immagine](https://user-images.githubusercontent.com/86877382/209212230-6de2dd38-9fc0-40fb-8fd6-8384167402f2.png)

**Comment by msalvati1997** [comment]
Here I show the other targets:
![immagine](https://user-images.githubusercontent.com/86877382/209212365-54c0a88a-68dd-4d88-bfd5-6a61ffee8f74.png)

**Comment by roda82** [comment]
Hello, 
Thank you for your feedback. Global consumption refers to the global consumption of the processor and it is required in order to estimate consumption of processes running on your physical computer server. I guess that your node is a physical server, therefore you only need to show on grafana consumption related to your containers and other applications by using cgroups that you have created for them as filters. 

Regards,

**Comment by msalvati1997** [comment]
Sorry for the redundancy.
So if I want to know the consumption of the  physical node I can filter only 'global' while the other filters I use to know the consumption of individual processes (like influxdb container).
Because my mistake was that to know the consumption of the node I was summing the total consumption taken by each filter. This was leading me to have excessive consumption.

Thank you very much for your answer.
